### ISSUE TITLE
specextract parameter exception not being handled nicely

### ISSUE THREAD

**Issue by kglotfelty** [cxcsds/ciao-contrib#731]
something's not working with how specextract handles a bad parameter name -- we are getting the full traceback:

```bash
% punlearn spectract
% specextract "4425/primary/acisf04425N005_evt2.fits.gz[sky=region(src.reg)]" bkg="4425/primary/acisf04425N005_evt2.fits.gz[sky=region(bkg.reg)]" out=foo weight- bkgresp- mode=h clob+
parammatch : parameter name bkg not uniq (bkg_binspec, bkgresp)
Traceback (most recent call last):
  File "/export/miniconda/envs/ciao-4.15/lib/python3.10/site-packages/ciao_contrib/param_wrapper.py", line 134, in open_param_file
    fp = pio.paramopen(None, mode, args)
OSError: paramopen() Could not execute paramopen

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/export/miniconda/envs/ciao-4.15/bin/specextract", line 62, in <module>
    import ciao_contrib._tools.specextract as spec
  File "/export/miniconda/envs/ciao-4.15/lib/python3.10/site-packages/ciao_contrib/_tools/specextract.py", line 64, in <module>
    elif paramio.pgetstr(open_param_file(sys.argv, toolname=__toolname__)["fp"],"parallel").lower() == "no" and paramio.pgeti(open_param_file(sys.argv, toolname=__toolname__)["fp"], "verbose") == 1:
  File "/export/miniconda/envs/ciao-4.15/lib/python3.10/site-packages/ciao_contrib/param_wrapper.py", line 137, in open_param_file
    raise IOError("There was a problem with the command-line parameter settings.")
OSError: There was a problem with the command-line parameter settings.
```

instead of just 

```bash
% bkg_fixed_counts m=32
parammatch : parameter name m not uniq (mode, max_radius)
# bkg_fixed_counts (09 November 2022): ERROR There was a problem with the command-line parameter settings.
```

it's like the `--debug`  flag is being set

**Comment by nplee** [comment]
I think this should be fixed in 4.15.1.

**Comment by kglotfelty** [comment]
Humm ... I grabbed the latest on the main branch on Monday and it's still showing the same thing

```git
commit 26981f49107088a7c3d58eb12a95f23e33685bfe (HEAD -> main, origin/main, origin/HEAD)
Author: Douglas Burke <dburke.gw@gmail.com>
Date:   Fri Jan 13 16:18:38 2023 -0500

    changelog for color_color
```

and `git pull` says' I'm up to date.

**Comment by nplee** [comment]
I have a simple fix in place now.  Don't think it's worth folding it into 4.15.1 and muck things up for CM, unless some additional critical changes need to be made to the tarball.
